apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tsmpfd6py-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tsmpfd6py-nodejs 
  name: tsmpfd6py-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tsmpfd6py-nodejs 
